### ISSUE TITLE
Total steps of training

### ISSUE THREAD

**Issue by amruz** [Justin-Tan/high-fidelity-generative-compression#16]
Thank you for the repository!
Regrading the total number of epochs of training, from the original paper they are training both part (autoencoder/hyperprior and GAN traininig) for 1 million steps. However in this implementation its trained for 10 epochs (If I am not wrong). Could you please explain this

**Comment by Justin-Tan** [comment]
Hi, https://github.com/Justin-Tan/high-fidelity-generative-compression/blob/master/train.py#L232

Optimization stops at the earlier of 1e6 steps/10 epochs. If you measure progress in epochs, this will depend on the size of your training set.

**Comment by amruz** [comment]
Thank you!
