### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by sbeckeriv** [Justin-Tan/high-fidelity-generative-compression#2]
Dearest Maintainer,

The pretrain model appears to be gone. Has it moved? If so what is the new download? If not I can cut a pr to remove the link.

Thanks
Dictated but not reviewed,
Becker

**Comment by Justin-Tan** [comment]
Oops, I accidentally trashed it, here is an updated model (medium setting).
I'll stick links to the high and low bitrate regimes in the README as well.

https://drive.google.com/open?id=1QNoX0AGKTBkthMJGPfQI0dT0_tnysYUb
