### ISSUE TITLE
When train in lower bitrates ( < 0.14)?

### ISSUE THREAD

**Issue by JXH-SHU** [Justin-Tan/high-fidelity-generative-compression#33]
Hi, thank you for your contributions. Following [https://github.com/Justin-Tan/high-fidelity-generative-compression/issues/12](url), I train the model on my own datasets (very small, contain 10,000 images with size 256*256). I change the values in the target_rate_map dict in default_config.py to [0.05,0.07,0.1]. However, the model shows higher bpp than the pretrained low model (0.14). Specially, the model trained with target rate 0.05 shows poor performance.  And the q_bpp of test is 0.325, while  that of train is 0.078. Could you give me some suggestions.

**Comment by JXH-SHU** [comment]
Fortunately, I found in the next GAN fine-tuning training (low model) that the value of bpp drops and meets expectations.

**Comment by yifeipet** [comment]
> Fortunately, I found in the next GAN fine-tuning training (low model) that the value of bpp drops and meets expectations.

Hello Shu,
What do you mean by "next GAN fine-tuning"? Have you changed the channel number of output of the encoder? 
Thank you!

Sincerely,
Yifei

**Comment by yifeipet** [comment]
> > Fortunately, I found in the next GAN fine-tuning training (low model) that the value of bpp drops and meets expectations.
>  @JXH-SHU
> Hello Shu,
> What do you mean by "next GAN fine-tuning"? Have you changed the channel number of output of the encoder?
> Thank you!
> 
> Sincerely, Yifei

**Comment by yifeipet** [comment]
> What do you mean by "next GAN fine-tuning"? Have you changed the channel number of output of the encoder?

@JXH-SHU 
Hello Shu,
What do you mean by "the next GAN fine-tuning"? Have you changed the channel number of output layer of the encoder?
Thank you!

Sincerely,
Yifei

**Comment by lzhzju** [comment]
> Fortunately, I found in the next GAN fine-tuning training (low model) that the value of bpp drops and meets expectations.

May I ask how you manage to do that?

**Comment by Joshpk29** [comment]
I believe they mean that q_bpp rates drop to expected levels after doing this code block.

```
# Train using full generator-discriminator loss
python3 train.py --model_type compression_gan --regime low --n_steps 1e6 --warmstart --ckpt path/to/base/checkpoint
```
