### ISSUE TITLE
’ train.py --model_type compression_gan --regime low --n_steps 1e6 --warmstart --ckpt path/to/base/checkpoint‘ did not work

### ISSUE THREAD

**Issue by cheng-linkai** [Justin-Tan/high-fidelity-generative-compression#34]
# Train using full generator-discriminator loss
python3 train.py --model_type compression_gan --regime low --n_steps 1e6 --warmstart --ckpt path/to/base/checkpoint
this command did not work for me ,after i changed it to 'python3 train.py --model_type compression_gan --regime low --n_steps 1e6 --warmstart -ckpt path/to/base/checkpoint' (--ckpt to -ckpt),it worked
maybe this can help somebody

**Comment by mepeichun** [comment]
Same problem. Thanks for your help.
